### ISSUE TITLE
Random site typos

### ISSUE THREAD

**Issue by mrhubbell** [f3peakcity/f3peakcity.github.io#18]
Homepage:

- Under 'Get a free workout' 2nd paragraph - "The workouts are **for** men of all..."
- Under 'Dive deeper' - "Check out 2nd **F (fellowship)** and 3rd F **(service)** opportunities..."
- Under 'Lead right' - "Whether it's plugging into an existing **effort** or starting..."

1st F:

- Half Dome - Hi Tempo **Hills** Boot Camp
- Move Off the Rails to Monday

3rd F: We had originally talked at Carpex SLT about including WWCM and TCP-Sawgrass on all new region 3rdF efforts. If Ryder is still on board for that...

- Add TCP Sawgrass: Every other Sunday @1400 - Location could simply be Downtown Cary multi-site. Description: Landscape multiple homes in support of The Carying Place. Slack: 3rdf-carying-place-tcp

New to F3:

- Do we need to explain what a "shovel flag" is?

Leadership: I feel this page needs a bit of an overarching summary at the top along the lines of...

- F3 is peer-led, and as part of that leadership, these PAX make up the Shared Leadership Team (SLT) in Peak City and focus on the invigoration of male community leadership. Whether that's thinking about new ways to motivate and encourage or helping launch new workouts, this team is here to support PAX as they grow and serve. 
- Nantan: Change all of Carpex to Peak City
- Expansion Q: Change to Region Ambassador - This role ensures we maintain intentional connections with the greater Carpex region.

**Comment by mikeyrcamp** [comment]
All issues fixed. Thanks @mrhubbell!
