### ISSUE TITLE
Carpex legacy hill picture.  Go POGL or go home!

### ISSUE THREAD

**Issue by BrianNewberry-Zoetis** [f3peakcity/f3peakcity.github.io#19]
Are you kidding me?  On the home page:

https://f3peakcity.github.io/img/workout-hill.jpeg
![image](https://user-images.githubusercontent.com/82182002/207902719-e26a5a18-2a87-4201-8974-cf9373f97e63.png)

That is the hill at Bond Park isn't it?  Can't we find a hill in Apex. . . tighten up Comz

**Comment by BrianNewberry-Zoetis** [comment]
Seriously though, the site is coming along nicely, great work guys and thanks for all your efforts

**Comment by mikeyrcamp** [comment]
🤣  thanks @BrianNewberry-Zoetis needed this today. That is going to be a water tower pic, soon enough.

**Comment by mikeyrcamp** [comment]
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/10994715/210192183-e4ef8b47-8e2d-4dd8-9c4d-2885d5de6373.png">

new pic!

**Comment by BrianNewberry-Zoetis** [comment]
nice!  I made center frame just like I planned
