### ISSUE TITLE
Buttons overlap on mobile devices

### ISSUE THREAD

**Issue by mikeyrcamp** [f3peakcity/f3peakcity.github.io#33]
https://stackoverflow.com/questions/11969427/margin-bottom-for-a-link-elements

![image](https://user-images.githubusercontent.com/10994715/210094182-cdb95c64-38af-4283-8674-bdfe6a690063.jpeg)

**Comment by artberger** [comment]
Theme PR: https://github.com/f3peakcity/beautifulhugo/pull/2
Website PR to bump theme: https://github.com/f3peakcity/f3peakcity.github.io/pull/36
