### ISSUE TITLE
Crosslink Peak City Q Sheet

### ISSUE THREAD

**Issue by mikeyrcamp** [f3peakcity/f3peakcity.github.io#37]
Right now we accomplish this with buttons on the website, and it would be awesome to accomplish this from the sheet as well for those that don't ever use the site but just open it in google sheets. Perhaps website we use the buttons, but when the sheet is opened sans website it has the links. Need to see if this is possible with google sheets.

**Comment by ugotmarcus** [comment]
Check out the Peak City Q-Sheet now and see if this is what you were looking for @mikeyrcamp.  This should work just fine.
