### ISSUE TITLE
Apply styling for Q sheet buttons in mobile view

### ISSUE THREAD

**Issue by natebynum20** [f3peakcity/f3peakcity.github.io#40]
When on a mobile browser, the Q sheet buttons don't appear nicely (touching each other and non-uniform). Apply styling to these when in mobile view.

**Comment by mikeyrcamp** [comment]
This is what I see, do you have a different expectation? I just fixed a similar issue yesterday in #33 

![image](https://user-images.githubusercontent.com/10994715/210384257-61deb6f5-9292-4ece-bbef-045a364c282d.png)
