### ISSUE TITLE
Post OM's backblasts

### ISSUE THREAD

**Issue by artberger** [f3peakcity/f3peakcity.github.io#60]
- [x] A-Team is Carpex, so not going to move this one. https://f3carpex.com/50-is-the-new-2/
- [x] https://f3carpex.com/when-are-we-going-to-start-disturbing-the-peace/
- [ ] https://f3carpex.com/its-a-jungle-at-lions-den/
- [ ] https://f3carpex.com/a-day-in-the-life/
- [ ] https://f3carpex.com/well-take-it-from-here-cardinal/

**Comment by ugotmarcus** [comment]
I've posted OM's two Backblast's that are applicable to Peak City.  His first one was A-Team so that being on Carpex is appropriate.  just need PR approval to post the Lion's Den one.
