### ISSUE TITLE
As an FNG I want a way to contact someone to get connected with F3

### ISSUE THREAD

**Issue by ugotmarcus** [f3peakcity/f3peakcity.github.io#8]
We need a "Contact Us" page.  It doesn't happen often, but about every 2 months we get an inquiry from and FNG asking how they get connected and start doing F3 etc...

As an FNG I want a way to contact someone to learn more about F3 Peak City and how to get started with my first workout.  

I want this message to be distributed to members of the Comz team, who in turn can distribute it to the FNQ Q's for proper response and follow up.

**Comment by artberger** [comment]
* Simplest way would probably be to embed a Google Form that is tied to the f3peakcity@gmail.com account.
* Other options could be using a different tool than Google Forms, such as Mailchimp. Seems like the complexity can vary. Some for example use custom layouts or shortcodes, esp. if we need the form in multiple places on the website.

**Comment by artberger** [comment]
@ugotmarcus here is the contact page, does this meet what you wanted? 
* Contact page: https://f3peakcity.github.io/contact/
* FNG page: https://f3peakcity.github.io/new-to-f3/

**Comment by ugotmarcus** [comment]
I like the content and the form, but can the form be made responsive on Mobile instead of being fixed width and require you to scroll side to side to see everything?
